apiVersion: v1
kind: Pod
metadata:
  labels:
    run: liveness-http
  name: liveness-http
spec:
  containers:
  - image: nginx:alpine
    name: liveness-http
    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 5 # wait before first probe
      periodSeconds: 5       # how often to probe
      successThreshold: 1    # minimum consecutive sucesses
      failureThreshold: 3    # minimum consecutive failures before acton
      timeoutSeconds: 5      # probe timeout
  dnsPolicy: ClusterFirst
  restartPolicy: Always