apiVersion: v1
kind: Pod
metadata:
  labels:
    run: liveness-exec
  name: liveness-exec
spec:
  containers:
  - image: busybox
    name: liveness-exec
    livenessProbe:
      exec:
        command:
          - /bin/sh
          - -c
          - "touch /tmp/healthy && rm -rf /tmp/healthy"
      periodSeconds: 30
      timeoutSeconds: 1
  dnsPolicy: ClusterFirst
  restartPolicy: Always