apiVersion: v1
kind: Pod
metadata:
  labels:
    run: secret-volume-pod
  name: secret-volume-pod
spec:
  containers:
  - image: nginx:alpine
    name: secret-volume-pod
    volumeMounts:
    - name: secrets
      mountPath: /etc/secrets
      readOnly: true
  volumes:
    - name: secrets
      secret:
        secretName: db-credentials
        defaultMode: 0400
  dnsPolicy: ClusterFirst
  restartPolicy: Always