#Create pod-requests-limits.yaml

apiVersion: v1
kind: Pod
metadata:
  name: requests-limits-pod
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        cpu: "250m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "256Mi"