apiVersion: v1
kind: ResourceQuota
metadata:
  name: mem-cpu-quota
  namespace: resource-quota-demo
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 512Mi
    limits.cpu: "2"
    limits.memory: 1Gi