apiVersion: v1
kind: Pod
metadata:
  name: tolerate-pod
  labels:
    app: nginx-tolerate
spec:
  tolerations:
  - key: "key1"
    operator: "Equal"
    value: "value1"
    effect: "NoSchedule"
  containers:
  - name: nginx
    image: nginx