services:
  terraform:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: terraform-env
    volumes:
      - ./terraform-data:/terraform
      - ~/.aws:/root/.aws:ro
    environment:
      - AWS_PROFILE
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_REGION
    stdin_open: true
    tty: true