FROM alpine:3.18

# Set Terraform version
ENV TERRAFORM_VERSION="1.11.4"

# Install dependencies
RUN apk add --update --no-cache \
    curl \
    bash \
    openssh \
    git \
    jq \
    vim \
    nano \
    unzip \
    python3 \
    py3-pip \
    groff \
    less

# Install AWS CLI v2
RUN python3 -m pip install --upgrade pip && \
    python3 -m pip install --no-cache-dir awscli

# Download and install Terraform
RUN curl -LO https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip && \
    unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip && \
    mv terraform /usr/local/bin/ && \
    rm terraform_${TERRAFORM_VERSION}_linux_amd64.zip

# Verify installation
RUN terraform version

WORKDIR /terraform

# Keep container running
ENTRYPOINT ["/bin/bash"]