services:
  localstack:
    container_name: localstack_main
    image: localstack/localstack:latest
    ports:
      - 127.0.0.1:4566:4566
      - 127.0.0.1:4510-4559:4510-4559
    environment:
      - DEBUG=1
      - PERSISTENCE=1
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=${TMPDIR:-/tmp/}localstack
    volumes:
      - ./localstack-data:/var/lib/localstack
      - ./localstack-logs:/var/log/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ../../../DevOps:/DevOps
    networks:
      - localstack-network
    
networks:
  localstack-network:
    driver: bridge