#create a daemonset for flannedD logging in namespace kube-system

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: flanneld-logging
  namespace: kube-system
  labels:
    app: flanneld-logging
    k8s-app: flanneld-logging
spec:
  selector:
    matchLabels:
      app: flanneld-logging
  template:
    metadata:
      labels:
        app: flanneld-logging
    spec:
      tolerations:
      # Make sure it can run on control plane nodes
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: flanneld-logger
        image: busybox:latest
        command:
        - /bin/sh
        - -c
        - >
          while true; do
            tail -n+1 -f /var/log/flanneld/flanneld.log;
            sleep 1;
          done
        volumeMounts:
        - name: flanneld-logs
          mountPath: /var/log/flanneld
        resources:
          limits:
            cpu: 100m
            memory: 200Mi
          requests:
            cpu: 50m
            memory: 100Mi
      volumes:
      - name: flanneld-logs
        hostPath:
          path: /var/log/flanneld
          type: DirectoryOrCreate
      serviceAccountName: flanneld
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flanneld
  namespace: kube-system